version: '3.2'

services:
  app:
      image: 'jc21/nginx-proxy-manager:latest'
      restart: unless-stopped
      ports:
        - '80:80'
        - '81:81'
        - '443:443'
      volumes:
        - ./data:/data
        - ./letsencrypt:/etc/letsencrypt

  nginx:
      build:
        context: ./nginx/
        dockerfile: Dockerfile
      volumes:
        - static_files:/user/src/app/staticfiles/
      ports:
        - "801:80"
        # - "443:443"
      depends_on:
        - app
        - web
      restart: "on-failure"
  backend:
    # restart: always
    ports:
      - "8001:8000"
    container_name: nth_backend
    command: gunicorn nth_backend.wsgi:application --bind 0.0.0.0:8000 --timeout 1800
    build:
      context: ./server/
      dockerfile: Dockerfile
    volumes:
      - static_files:/user/src/app/staticfiles/
      - ./server/db.sqlite3:/user/src/app/db.sqlite3
      - ./server/:/user/src/app/
  
    env_file:
      - ./server/.env/dev.env


volumes:
  static_files:
